import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'
import prettier from 'eslint-config-prettier/flat'
import { defineConfig, globalIgnores } from 'eslint/config'
import { createRequire } from 'node:module'

const { version: reactVersion } = createRequire(import.meta.url)(
    'react/package.json'
)

const eslintConfig = defineConfig([
    ...nextVitals,
    ...nextTs,
    prettier,
    // eslint-plugin-react's `version: 'detect'` calls context.getFilename(),
    // which ESLint 10 removed - pin the version to skip detection.
    { settings: { react: { version: reactVersion } } },
    {
        rules: {
            '@typescript-eslint/no-unused-vars': [
                'error',
                { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }
            ]
        }
    },
    // Override default ignores of eslint-config-next.
    globalIgnores([
        // Default ignores of eslint-config-next:
        '.next/**',
        'out/**',
        'build/**',
        'next-env.d.ts',
        // Generated by `sanity typegen generate`
        'src/sanity/types.ts'
    ])
])

export default eslintConfig
